### ISSUE TITLE
Too many garbage in authorized_keys

### ISSUE THREAD

**Issue by halaei** [dan-v/awslambdaproxy#17]
### Prerequisites

* [ ] I am running the [latest version](https://github.com/dan-v/awslambdaproxy/releases) of awslambdaproxy (version 13 tested, couldn't install version 14)
* [x] I am have read the [README](https://github.com/dan-v/awslambdaproxy#usage) instructions and the [FAQ](https://github.com/dan-v/awslambdaproxy#faq)

### Description
I have some version of this project on a server. I noticed it created 6000 .ssh/authorized_keys. I don't know how to check the version, the command prompt doesn't seem to give me that info. I also installed version 13 on a new instance. So far it created 2 keys. 

### Steps to Reproduce
Probably running with low -f param or running the server under supervisor and periodically restart the daemon increase the amount of left over keys.

**Expected behavior:** I guess this package should safely clear the keys after it is done with them.

**Actual behavior:** Over time authorized_keys will get huge.

### Environment
```
# version 13
awslambdaproxy run -r us-west-2,us-west-1,us-east-1,us-east-2,ca-central-1,eu-central-1,eu-west-1,eu-west-2,eu-west-3 -f 360s
```

**Comment by dan-v** [comment]
Sorry for delayed response @halaei. This indeed seems like a bug. I'm guessing I never see this because I'm using the docker image, so it doesn't ever touch the host machine's authorized key. 

Ah, also I realized I uploaded the wrong artifact for v0.0.14 which is why you couldn't run that. This won't fix your issue though.
